### PR TITLE
Adds remark-lint and CI

### PR DESCRIPTION
**Pull request by sobolevn**
That is still WIP, I have to add new contributing rules, fix some styles, and add travis badge.

### CODE REVIEW

**Comment by rtrv** [comment]
@sobolevn mark it WIP, please, while it's not ready

**Comment by sobolevn** [comment]
Done!

```
» npm run test

> elixir-docs-ru@1.0.0 test /Users/sobolev/Documents/github/elixir-docs-ru
> remark *.md meta/ mix-otp/ -f

README.md: no issues found
alias-require-and-import.md: no issues found
basic-operators.md: no issues found
basic-types.md: no issues found
binaries-strings-and-char-lists.md: no issues found
case-cond-and-if.md: no issues found
comprehensions.md: no issues found
enumerables-and-streams.md: no issues found
erlang-libraries.md: no issues found
index.md: no issues found
io-and-the-file-system.md: no issues found
keywords-and-maps.md: no issues found
meta/domain-specific-languages.md: no issues found
meta/macros.md: no issues found
meta/quote-and-unquote.md: no issues found
mix-otp/agent.md: no issues found
mix-otp/dependencies-and-umbrella-apps.md: no issues found
mix-otp/distributed-tasks-and-configuration.md: no issues found
mix-otp/docs-tests-and-with.md: no issues found
mix-otp/ets.md: no issues found
mix-otp/genserver.md: no issues found
mix-otp/introduction-to-mix.md: no issues found
mix-otp/supervisor-and-application.md: no issues found
mix-otp/task-and-gen-tcp.md: no issues found
module-attributes.md: no issues found
modules-and-functions.md: no issues found
pattern-matching.md: no issues found
processes.md: no issues found
protocols.md: no issues found
recursion.md: no issues found
sigils.md: no issues found
structs.md: no issues found
try-catch-and-rescue.md: no issues found
typespecs-and-behaviours.md: no issues found
where-to-go-next.md: no issues found
```

**Comment by rtrv** [comment]
@sobolevn I actually would prefer "linux way" output: no need to print files with no issues found, only ones with problems. And you can unmark it WIP

**Comment by sobolevn** [comment]
You can suggest to change the output here: https://github.com/wooorm/remark-lint

**Comment by rtrv** [comment]
Ok, I see, it's default output. So I'm merging this

**Pull request merged**
